# Generated by Django 3.2.15 on 2022-11-24 13:03

import TCCApp.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('TCCApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ultimo_nome',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=2, max_length=256),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id_upload', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=TCCApp.models.upload_image_mockup)),
                ('nome', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mockup_Usuario', to='TCCApp.users')),
            ],
        ),
    ]
